#if !canImport(ObjectiveC)
import XCTest

extension TypedCatalogTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypedCatalogTests = [
        ("testFailsWithoutParameters", testFailsWithoutParameters),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TypedCatalogTests.__allTests__TypedCatalogTests),
    ]
}
#endif
